### ISSUE TITLE
Windows Port

### ISSUE THREAD

**Issue by bistcuite** [Alistair-Bell/holyc-compiler#6]
When holyc supports windows ?

**Comment by Alistair-Bell** [comment]
I do admit an windows port would be cool. My focus is for an unix like port as.
I actually have a unix like machine to use.
The executable format (PE) is different than the unix elf and would require 2 different bytecode to object code algorithms.
More systems use the elf format -> Linux, BSD, Solaris, etc
Windows is not reliably posix and may be missing some libraries to compile on. Possibly a cross compiler first will work.

Ultimately I would love to have a windows port but the target platform for now is unix elf systems.
